name: Build

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Build apt-repo
        run: |
          git clone https://github.com/Arkanic/apt-repo --depth=1
          cd apt-repo
          sudo make
          cd ../
          rm -rf apt-repo
      
      - name: build
        run: termux-apt-repo deb dist
        
      - name: clean
        run: |
          rm -rf deb
        
      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./extras
