name: Build

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Python
        uses: actions/setup-python@v2.2.2
      
      - name: install termux-apt-repo
        run: pip3 install termux-apt-repo
      
      - name: build
        run: termux-apt-repo deb dist
      
      - name: mv
        run: |
          cd dist
          mv termux/* .
        
      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
